export const EN = [
    {
        mainDisplay:'\`',
        mainValue:'\`',
        altDisplay:'~',
        altValue:'~',
        space:1     
    }, 
    {
        mainDisplay:'1',
        mainValue:'1',
        altDisplay:'!',
        altValue:'!',
        space:1      
    },
    {
        mainDisplay:'2',
        mainValue:'2',
        altDisplay:'@',
        altValue:'@',
        space:1      
    },
    {
        mainValue:'3',
        mainDisplay:'3',
        altDisplay:'#',
        altValue:'#',
        space:1      
    },
    {
        mainDisplay:'4',
        mainValue:'4',
        altDisplay:'$',
        altValue:'$',
        space:1      
    },
    {
        mainValue:'5',
        mainDisplay:'5',
        altValue:'%',
        altDisplay:'%',
        space:1      
    },
    {
        mainValue:'6',
        mainDisplay:'6',
        altValue:'6',
        altDisplay:'6',
        space:1      
    },
    {
        mainDisplay:'7',
        mainValue:'7',
        altDisplay:'&',
        altValue:'&',
        space:1      
    },
    {
        mainValue:'8',
        mainDisplay:'8',
        altValue:'*',
        altDisplay:'*',
        space:1      
    },
    {
        mainValue:'9',
        mainDisplay:'9',
        altValue:'(',
        altDisplay:'(',
        space:1      
    },
    {
        mainValue:'0',
        mainDisplay:'0',
        altValue:')',
        altDisplay:')',
        space:1      
    },
    {
        mainValue:'-',
        mainDisplay:'-',
        altValue:'_',
        altDisplay:'_',
        space:1      
    },
    {
        mainValue:'=',
        mainDisplay:'=',
        altValue:'+',
        altDisplay:'+',
        space:1      
    },
    {
        mainValue:'Backspace',
        mainDisplay:'&#8656;',
        altValue:'Backspace',
        altDisplay:'&#8656;',
        space:2      
    },
    {
        mainValue:'Tab',
        mainDisplay:'&#8646;',
        altValue:'Tab',
        altDisplay:'&#8646;',
        space:2      
    },
    {
        mainValue:'q',
        mainDisplay:'q',
        altValue:'Q',
        altDisplay:'Q',
        space:1      
    },
    {
        mainValue:'w',
        mainDisplay:'w',
        altValue:'W',
        altDisplay:'W',
        space:1      
    },
    {
        mainValue:'e',
        mainDisplay:'e',
        altValue:'E',
        altDisplay:'E',
        space:1      
    },
    {
        mainValue:'r',
        mainDisplay:'r',
        altValue:'R',
        altDisplay:'R',
        space:1      
    },
    {
        mainValue:'t',
        mainDisplay:'t',
        altValue:'T',
        altDisplay:'T',
        space:1      
    },
    {
        mainValue:'y',
        mainDisplay:'y',
        altValue:'Y',
        altDisplay:'Y',
        space:1      
    },
    {
        mainValue:'u',
        mainDisplay:'u',
        altValue:'U',
        altDisplay:'U',
        space:1      
    },
    {
        mainValue:'i',
        mainDisplay:'i',
        altValue:'I',
        altDisplay:'I',
        space:1      
    },
    {
        mainValue:'o',
        mainDisplay:'o',
        altValue:'O',
        altDisplay:'O',
        space:1      
    },
    {
        mainValue:'p',
        mainDisplay:'p',
        altValue:'P',
        altDisplay:'P',
        space:1      
    },
    {
        mainValue:'[',
        mainDisplay:'[',
        altValue:'{',
        altDisplay:'{',
        space:1      
    },
    {
        mainValue:']',
        mainDisplay:']',
        altDisplay:'}',
        altValue:'}',
        space:1      
    },
    {
        mainValue:'\\',
        mainDisplay:'\\',
        altValue:'|',
        altDisplay:'|',
        space:1      
    },
    {
        mainValue:'CapsLock',
        mainDisplay:'CapsLock',
        altValue:'CapsLock',
        altDisplay:'CapsLock',
        space:2      
    },
    {
        mainValue:'a',
        mainDisplay:'a',
        altDisplay:'A',
        altValue:'A',
        space:1      
    },
    {
        mainValue:'s',
        mainDisplay:'s',
        altDisplay:'S',
        altValue:'S',
        space:1      
    },
    {
        mainValue:'d',
        mainDisplay:'d',
        altDisplay:'D',
        altValue:'D',
        space:1      
    },
    {
        mainValue:'f',
        mainDisplay:'f',
        altDisplay:'F',
        altValue:'F',
        space:1      
    },
    {
        mainValue:'g',
        mainDisplay:'g',
        altValue:'G',
        altDisplay:'G',
        space:1      
    },
    {
        mainValue:'h',
        mainDisplay:'h',
        altDisplay:'H',
        altValue:'H',
        space:1      
    },
    {
        mainValue:'j',
        mainDisplay:'j',
        altValue:'J',
        altDisplay:'J',
        space:1      
    },
    {
        mainValue:'k',
        mainDisplay:'k',
        altDisplay:'K',
        altValue:'K',
        space:1      
    },
    {
        mainValue:'l',
        mainDisplay:'l',
        altDisplay:'L',
        altValue:'L',
        space:1      
    },
    {
        mainValue:';',
        mainDisplay:';',
        altValue:':',
        altDisplay:':',
        space:1      
    },
    {
        mainDisplay:'\'',
        mainValue:'\'',
        altValue:'\"',
        altDisplay:'\"',
        space:1      
    },
    {
        mainValue:'Enter',
        mainDisplay:'&#10550;',
        altValue:'Enter',
        altDisplay:'&#10550;',
        space:2      
    },
    {
        mainValue:'Shift',
        mainDisplay:'Shift',
        altDisplay:'Shift',
        altValue:'Shift',
        space:2      
    },
    {
        mainValue:'z',
        mainDisplay:'z',
        altDisplay:'Z',
        altValue:'Z',
        space:1      
    },
    {
        mainValue:'x',
        mainDisplay:'x',
        altDisplay:'X',
        altValue:'X',
        space:1      
    },
    {
        mainValue:'c',
        mainDisplay:'c',
        alt:'C',
        alt:'C',
        space:1      
    },
    {
        mainValue:'v',
        mainDisplay:'v',
        altDisplay:'V',
        altValue:'V',
        space:1      
    },
    {
        mainValue:'b',
        mainDisplay:'b',
        altDisplay:'B',
        altValue:'B',
        space:1      
    },
    {
        mainValue:'n',
        mainDisplay:'n',
        altDisplay:'N',
        altValue:'N',
        space:1      
    },
    {
        mainValue:'m',
        mainDisplay:'m',
        altDisplay:'M',
        altValue:'M',
        space:1      
    },
    {
        mainValue:',',
        mainDisplay:',',
        altValue:'<',
        altDisplay:'<',
        space:1      
    },
    {
        mainValue:'.',
        mainDisplay:'.',
        altDisplay:'>',
        altValue:'>',
        space:1      
    },
    {
        mainValue:'\/',
        mainDisplay:'\/',
        altValue:'?',
        altDisplay:'?',
        space:1      
    },
    {
        mainValue:'ArrowUp',
        mainDisplay:'&#8657;',
        altValue:'ArrowUp',
        altDisplay:'&#8657;',
        space:1      
    },
    {
        mainValue:'Shift',
        mainDisplay:'Shift',
        altDisplay:'Shift',
        altValue:'Shift',
        space:2      
    },
    {
        mainValue:'Control',
        mainDisplay:'Ctrl',
        altValue:'Control',
        altDisplay:'Ctrl',
        space:2     
    },
    {
        mainValue:'Win',
        mainDisplay:'Win',
        altDisplay:'Win',
        altValue:'Win',
        space:1     
    },
    {
        mainValue:'Alt',
        mainDisplay:'Alt',
        altValue:'Alt',
        altDisplay:'Alt',
        space:1     
    },
    {
        mainValue:'Spacebar',
        mainDisplay:'  ',
        altValue:'Spacebar',
        altDisplay:'  ',
        space:6     
    },
    {
        mainValue:'Alt',
        mainDisplay:'Alt',
        altValue:'Alt',
        altDisplay:'Alt',
        space:1     
    },
    {
        mainValue:'ArrowLeft',
        mainDisplay:'&#8656;',
        altValue:'ArrowLeft',
        altDisplay:'&#8656;',
        space:1      
    },
    {
        mainValue:'ArrowDown',
        mainDisplay:'&#8659;',
        altValue:'ArrowDown',
        altDisplay:'&#8659;',
        space:1    
    },
    {
        mainValue:'ArrowRight',
        mainDisplay:'&#8658;',
        altValue:'ArrowDown',
        altDisplay:'&#8658;',
        space:1    
    },
]
